---
version: "2.1"
services:

  nodejs:
    image: dev_nodejs
    container_name: dev_nodejs
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t    

    volumes:
      - "./..:/scripts" 
      - "/media/data/shared_folders/lfs2:/lfs"
      - "/media/data/shared_folders:/shared_folders"
      - "~/.ssh:/home/lfs/.ssh"
      - "/media/data/project_my:/project_my"

    ports:
      - 3000:3000
      - 5000:5000

      
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/